title: Riccardo Zecchini – Designer, climbing and outdoor lover
description: Hi there, I’m Riccardo. User Experience specialist and front-end designer.
baseurl: ""
url: "https://www.riccardozecchini.com"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
